---
title: "DM1 Dataviz"
author: "Valentine BERTHIER"
date: "2024-02-18"
output: html_document
---

```{r}
rm(list=ls())
```


```{r}
# Chargement du package qui va nous permettre de récupérer les données diffusées dans le cadre de tidytuesday
library(tidytuesdayR)

#Autre package utilisés dans la suite du code 
library(dplyr)
library(ggplot2)

#library(tidyverse)
#library(patchwork)
#library(showtext)
#font_add_google("Playfair Display")
#font_add_google("Poppins")
#showtext_opts(dpi = 320)
#showtext_auto()

```

```{r}
# Pour charger le jeu de données qui nous intéresse, il suffit de mentionner la date de diffusion dans la fonction tt_load du package tidytuesdayR
tuesdata <- tidytuesdayR::tt_load('2022-05-24')

# Afin d'effectuer un graphique sur les mêmes données que celui critiqué, nous ne gardons que la base de données du tournoi 'sevens'

sevens <- tuesdata$sevens


```

```{r}
# Visualisons ce jeu de données

str(sevens)
colnames(sevens)

# Nous allons nous intéresser aux variables `team_1`, `score_1`, `score_2`,`team_2` et `winner`,`loser`

```
```{r}
#On souhaite répondre à la même question que celle du graphe critiqué, c'est à dire : 
# Quelle a été la performance des 10 équipes du tournois ayant joué le plus de match
# Analysons nos données
str(sevens)

min(sevens$date)
max(sevens$date)

unique(sevens$tournament) # beaucoup de tournois représentés 

# on remarque qu'il y a des équipes Néo-zélandaises ayant fait des match sous un autre nom que "New Zealand', on les regroupent toutes sous le même nom 
sevens <- sevens %>%
  mutate(winner = case_when(str_detect(winner, "New Zealand") ~ "New Zealand",
                            TRUE ~ winner))
# sans regrouper par année pour voir qui a joué le plus de match


winners <- sevens %>%
  group_by(winner) %>%
  count(winner) %>%
  rename(team = winner,
         total_wins = n) %>%
  ungroup()

losers <- sevens %>%
  group_by(loser) %>%
  count(loser) %>%
  rename(team = loser,
         total_loss = n) %>%
  ungroup()

pays <- full_join(winners, losers, by = "team") %>%
  mutate(total_games = total_wins + total_loss)%>%
  arrange(desc(total_games))%>%
  head(10)%>%
  select(team)

```

# Idée en regroupant par année
```{r}



# regroupons par année : 

sevens_annee <- sevens %>%
  mutate(annee=str_sub(date,1,4))

winners <- sevens_annee %>%
  group_by(winner,annee)%>%
  count(winner)%>%
  rename(team = winner,
         total_wins = n) %>%
  ungroup()

losers <- sevens_annee %>%
  group_by(loser,annee)%>%
  count(loser)%>%
  rename(team = loser,
         total_loss = n) %>%
  ungroup()
  

# Calculons le nombre de matchs joués par chaque équipe


winlos <- full_join(winners, losers, by = c("team","annee"))

winlos$total_loss[which(is.na(winlos$total_loss))]<-0
winlos$total_wins[which(is.na(winlos$total_wins))]<-0


# En ayant gardé les années, on se rend compte qu'on n'observe pas les mêmes que le graphe à critiquer
# on souhaite tout de même répondre à la même question que l'autre graphe : les 10 pays ayant joué le plus de matchs mais sur toutes les années donc on regarde qui ils sont 

  
winlos<-winlos%>%
  mutate(total_games_parA=total_wins+total_loss)%>%
  arrange(desc(total_games_parA))

winlos%>%
  select(team,)%>%
  unique()%>%
  head(10)

top10<-pays$team
data<-winlos%>%
  group_by(team)%>%
  mutate(Total=sum(total_games_parA))%>%
  arrange(desc(Total))%>%
  filter(team %in% top10)

data<-winlos%>%
  group_by(team)%>%
  mutate(TotalG=sum(total_games_parA),TotalW=sum(total_wins))

top10<-data%>%
  arrange(desc(TotalG))%>%
  select(team,TotalG)%>%
  unique()%>%
  head(10)

top10<-top10$team

final<-data%>%
  arrange(desc(TotalW))%>%
  filter(team %in% top10)

final_perc<-final%>%
  mutate(PW=(TotalW*100)/TotalG)





```
## Représentation 
```{r}
final%>%
  ggplot(aes(x=annee,y=total_wins,fill=team))+
  geom_point()


# changer la couleur des points en fonction du pays, 
# ajouter une ligne reliant les points pour voir l'evolution

```




```{r}
winlos%>%
  filter(team=='New Zealand')%>%
  summary(sum(total_games))
```



